version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: soufienessalah/devops-foyer:3.0.1
    networks:
      - dev-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: foyer
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - dev-network

  backend:
    build: .
    container_name: backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/foyer?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
    ports:
      - "8083:8083"
    depends_on:
      - mysql
    networks:
      - dev-network

  frontend:
    build: ./chambre-frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - dev-network

volumes:
  mysql-data:

networks:
  dev-network:
    driver: bridge
